# Generated by Django 3.0.2 on 2020-02-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathem', '0003_comment_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplesErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=50, verbose_name='Имя или ник автора сообщения')),
                ('people_message', models.TextField(max_length=200, verbose_name='Текст его сообщения')),
                ('date_message', models.DateTimeField(verbose_name='Дата сообщения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathem.Question')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
