# Generated by Django 3.0.2 on 2020-02-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathem', '0005_auto_20200210_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
