# Generated by Django 3.0.2 on 2020-02-14 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathem', '0007_solvedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedquestion',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solvedquestion',
            name='solved_question',
            field=models.CharField(max_length=50, verbose_name='Список решенных задач'),
        ),
    ]
