# Generated by Django 3.0.2 on 2020-02-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathem', '0011_auto_20200214_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wrong_solved_task',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
